spring:
  application:
    name: simple_mail_server_example

  mail:
    protocol: smtp
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: hatinproject1@gmail.com
    password: kobnxzxfuyqmqere
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true